spring:
  datasource:
    url: jdbc:mysql://oracle.wpl.kro.kr:3306/wpl_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: wpl
    password: wpl
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

app:
  FileProperties:
    root: /wpl/files

logging:
  level:
    org.hibernate.sql: debug